plugins {
    id 'com.axelor.app'
}

axelor {
    title = 'ODC Sales'
    description = 'ODC sales module'
}

dependencies {
    api project(':modules:odc-organization')
    api project(':modules:odc-reference-data')
    api project(':modules:odc-party')
    api project(':modules:odc-tax')
    api project(':modules:odc-catalog')
    api project(':modules:odc-pricing')
    api project(':modules:odc-document-control')
}
