package com.odc.sales.service;
import com.axelor.auth.AuthUtils;import com.axelor.auth.db.User;import com.axelor.db.JPA;import com.axelor.i18n.I18n;import com.google.inject.Inject;import com.google.inject.persist.Transactional;
import com.odc.document.service.DocumentSequenceService;import com.odc.document.service.UserPointAssignmentService;import com.odc.sales.db.SalesInvoice;import com.odc.sales.db.repo.SalesInvoiceRepository;import jakarta.persistence.LockModeType;import java.time.LocalDateTime;import java.util.Objects;
public class SalesInvoiceConfirmationServiceImpl implements SalesInvoiceConfirmationService{
 private final SalesInvoiceRepository repository;private final SalesInvoiceService invoices;private final SalesInvoiceLineService lines;private final SalesInvoicePricingService pricing;private final SalesInvoiceTaxService taxes;private final SalesInvoiceCalculationService calculation;private final DocumentSequenceService sequences;private final UserPointAssignmentService pointAccess;
 @Inject public SalesInvoiceConfirmationServiceImpl(SalesInvoiceRepository r,SalesInvoiceService i,SalesInvoiceLineService l,SalesInvoicePricingService p,SalesInvoiceTaxService t,SalesInvoiceCalculationService c,DocumentSequenceService s,UserPointAssignmentService a){repository=r;invoices=i;lines=l;pricing=p;taxes=t;calculation=c;sequences=s;pointAccess=a;}
 @Transactional public SalesInvoiceConfirmationResult confirm(SalesInvoice requested){
  SalesInvoice i=lock(requested);User u=AuthUtils.getUser();if(u==null)throw err("Authenticated user is required.");lines.lockActiveLines(i);validateForConfirmation(i);pointAccess.requireUserAccess(u,i.getDocumentSeries().getPointOfSale());pricing.refreshPrices(i);taxes.refreshTaxes(i);SalesInvoiceTotals totals=calculation.recalculate(i);if(totals.lineCount()<1||totals.grandTotal().signum()<=0)throw err("Invoice totals are invalid.");
  var reservation=sequences.reserve(i.getDocumentSeries(),SalesInvoice.class.getName(),i.getId(),"sales-invoice:"+i.getId());reservation=sequences.consume(reservation,i.getId());
  i.setDocumentSequenceReservation(reservation);i.setDocumentNo(reservation.getDocumentNo());i.setStatus("CONFIRMED");i.setConfirmedAt(LocalDateTime.now());i.setConfirmedBy(u);repository.save(i);
  return new SalesInvoiceConfirmationResult(i,i.getDocumentNo(),reservation,i.getConfirmedAt(),u,totals);
 }
 public void validateForConfirmation(SalesInvoice i){if(i==null||i.getId()==null)throw err("Persisted sales invoice is required.");if(Boolean.TRUE.equals(i.getArchived())||!"DRAFT".equals(i.getStatus()))throw err("Only a draft invoice can be confirmed.");invoices.validateCommon(i);if(i.getDueDate()==null)throw err("Due date is required.");if(i.getDocumentSeries()==null)throw err("Document series is required.");var s=i.getDocumentSeries();if(Boolean.TRUE.equals(s.getArchived())||!Boolean.TRUE.equals(s.getActive())||!"SALES_INVOICE".equals(s.getDocumentType()))throw err("Document series is invalid.");var establishment=s.getEmissionEstablishment();if(establishment==null||!same(establishment.getBranch(),i.getBranch())||!same(s.getPointOfSale().getEmissionEstablishment(),establishment))throw err("Document series belongs to another branch.");if(i.getDocumentNo()!=null||i.getDocumentSequenceReservation()!=null)throw err("Invoice already has document numbering.");if(lines.findActiveLines(i).isEmpty())throw err("Invoice must contain at least one line.");}
 protected SalesInvoice lock(SalesInvoice v){if(v==null||v.getId()==null)throw err("Persisted sales invoice is required.");return JPA.em().find(SalesInvoice.class,v.getId(),LockModeType.PESSIMISTIC_WRITE);}
 private boolean same(com.axelor.db.Model a,com.axelor.db.Model b){return a==b||a!=null&&b!=null&&a.getId()!=null&&Objects.equals(a.getId(),b.getId());}
 private IllegalArgumentException err(String m){return new IllegalArgumentException(I18n.get(m));}
}
